services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - backend
  gameframex:
    #记得要改好版本号，或者直接用最新的版本latest
    image: crpi-rgg694lcnk3c8wd8.cn-guangzhou.personal.cr.aliyuncs.com/gameframex-lgj/gameframex:latest
#    image: gameframex.launcher:1.0.0.0
    container_name: gameframex
    ports:
      # APM 端口
      - "29090:29090"
      # TCP 端口
      - "29100:29100"
      # WebSocket 端口
      - "29110:29110"
      # HTTP 端口
      - "28080:28080"
    environment:
      - ServerType=Game
      - ServerId=1000
      - APMPort=29090
      - InnerIp=0.0.0.0
      - InnerPort=29100
      - OuterIp=0.0.0.0
      - OuterPort=29100
      - MinModuleId=10
      - MaxModuleId=9999
      - WsPort=29110
      - DiscoveryCenterIp=127.0.0.1
      - DiscoveryCenterPort=10001
      - HttpCode=inner_httpcode
      - DataBaseUrl=mongodb://admin:admin@mongodb:27017
      - DataBaseName=gameframex
      - IsDebug=true
      - IsDebugSend=true
      - IsDebugReceive=true
      - IsDebugReceive=true
      - HttpPort=28080
    networks:
      - backend
    volumes:
      - "./running/hotfix:/app/hotfix"
      - "./running/json:/app/json"
      - "./running/logs:/app/logs"
networks:
  backend:
    name: gameframex-backend
    driver: bridge